# Generated by Django 5.0.7 on 2025-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('reset', 'Reset Password')], default='register', max_length=20),
        ),
    ]
