# Generated by Django 5.0.7 on 2025-12-04 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_pic_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical')], max_length=20)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_ratinghistory',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'mode', '-date'], name='accounts_ra_user_id_82c5e3_idx')],
                'unique_together': {('user', 'mode', 'date')},
            },
        ),
    ]
