# Generated by Django 5.0.7 on 2025-12-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ratinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
