# Generated by Django 5.2.11 on 2026-03-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_refreshsession"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ratinghistory",
            new_name="accounts_ra_user_id_484859_idx",
            old_name="accounts_ra_user_id_mode_recorded_at_idx",
        ),
        migrations.RenameIndex(
            model_name="refreshsession",
            new_name="accounts_re_user_id_0a6231_idx",
            old_name="accounts_re_user_id_955646_idx",
        ),
        migrations.RenameIndex(
            model_name="refreshsession",
            new_name="accounts_re_expires_9602e4_idx",
            old_name="accounts_re_expires_cbc72a_idx",
        ),
        migrations.RenameIndex(
            model_name="refreshsession",
            new_name="accounts_re_last_us_2decfa_idx",
            old_name="accounts_re_last_us_603ffe_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="bot_engine",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bot_play_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bot_avatar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
