# Generated by Django 5.2.10 on 2026-02-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("game_challenge", "Game Challenge"),
                    ("game_move", "Game Move"),
                    ("friend_request", "Friend Request"),
                    ("message", "Message"),
                    ("rematch", "Rematch"),
                    ("rematch_requested", "Rematch Requested"),
                    ("challenge_rejected", "Challenge Rejected"),
                    ("challenge_expired", "Challenge Expired"),
                    ("tournament_start", "Tournament Start"),
                    ("tournament_result", "Tournament Result"),
                ],
                max_length=50,
            ),
        ),
    ]
