# Generated by Django 5.0.7 on 2025-11-30 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_control', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical'), ('custom', 'Custom')], default='blitz', max_length=20)),
                ('initial_time_seconds', models.IntegerField(default=300)),
                ('increment_seconds', models.IntegerField(default=2)),
                ('white_time_seconds', models.IntegerField(default=300)),
                ('black_time_seconds', models.IntegerField(default=300)),
                ('white_increment_seconds', models.IntegerField(default=2)),
                ('black_increment_seconds', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('1-0', 'White'), ('0-1', 'Black'), ('1/2-1/2', 'Draw'), ('*', 'Unfinished')], default='*', max_length=10)),
                ('moves', models.TextField(blank=True, help_text='PGN moves in SAN, space separated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_created', to=settings.AUTH_USER_MODEL)),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
