# Generated by Django 5.0.7 on 2025-12-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_tournamentgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchmakingQueue',
        ),
    ]
