# Generated by Django 5.0.7 on 2025-12-04 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_prediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rated',
            field=models.BooleanField(default=True, help_text='Whether this game affects player ratings'),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematches', to='games.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='password',
            field=models.CharField(blank=True, help_text='Entry code for private tournaments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rated',
            field=models.BooleanField(default=True, help_text='Whether this tournament affects player ratings'),
        ),
    ]
