# Generated by Django 4.2 on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0013_game_rematch_requested_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigiQuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(max_length=64, unique=True)),
                ("tag", models.CharField(db_index=True, max_length=120)),
                ("question", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("answer_index", models.PositiveSmallIntegerField()),
                ("answer_text", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="DigiQuizRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_date", models.DateField(help_text="Round date in IST", unique=True)),
                ("join_open_at", models.DateTimeField()),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("join_open", "Join Open"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("is_official", models.BooleanField(default=False)),
                ("questions_count", models.PositiveSmallIntegerField(default=20)),
                ("question_duration_seconds", models.PositiveSmallIntegerField(default=20)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-start_at"]},
        ),
        migrations.CreateModel(
            name="DigiQuizRoundQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_no", models.PositiveSmallIntegerField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_entries",
                        to="games.digiquizquestion",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_questions",
                        to="games.digiquizround",
                    ),
                ),
            ],
            options={"ordering": ["question_no"]},
        ),
        migrations.CreateModel(
            name="DigiQuizParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("joined_question_no", models.PositiveSmallIntegerField(default=1)),
                ("total_points", models.IntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                ("resolved_count", models.PositiveIntegerField(default=0)),
                ("total_answer_time_ms", models.PositiveIntegerField(default=0)),
                ("last_answer_at", models.DateTimeField(blank=True, null=True)),
                ("rating_applied", models.BooleanField(default=False)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="games.digiquizround",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digiquiz_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_points", "-correct_count", "total_answer_time_ms", "joined_at"],
            },
        ),
        migrations.CreateModel(
            name="DigiQuizAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_no", models.PositiveSmallIntegerField()),
                ("selected_index", models.SmallIntegerField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("wrong", "Wrong"),
                            ("timeout", "Timeout"),
                            ("missed_late_join", "Missed (Late Join)"),
                        ],
                        max_length=24,
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="games.digiquizparticipation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="games.digiquizquestion",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="games.digiquizround",
                    ),
                ),
            ],
            options={"ordering": ["question_no"]},
        ),
        migrations.CreateModel(
            name="DigiQuizRatingHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating_before", models.IntegerField()),
                ("round_delta", models.IntegerField()),
                ("rating_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_history_entry",
                        to="games.digiquizparticipation",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_history",
                        to="games.digiquizround",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digiquiz_rating_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["round__start_at"]},
        ),
        migrations.AddConstraint(
            model_name="digiquizroundquestion",
            constraint=models.UniqueConstraint(fields=("round", "question_no"), name="uq_digiquiz_round_question_no"),
        ),
        migrations.AddConstraint(
            model_name="digiquizroundquestion",
            constraint=models.UniqueConstraint(fields=("round", "question"), name="uq_digiquiz_round_question_unique"),
        ),
        migrations.AddConstraint(
            model_name="digiquizparticipation",
            constraint=models.UniqueConstraint(fields=("round", "user"), name="uq_digiquiz_participation_round_user"),
        ),
        migrations.AddConstraint(
            model_name="digiquizanswer",
            constraint=models.UniqueConstraint(
                fields=("participation", "question_no"),
                name="uq_digiquiz_answer_participation_question",
            ),
        ),
        migrations.AddIndex(
            model_name="digiquizanswer",
            index=models.Index(fields=["round", "question_no"], name="games_digiq_round_i_3496de_idx"),
        ),
        migrations.AddIndex(
            model_name="digiquizanswer",
            index=models.Index(
                fields=["participation", "question_no"],
                name="games_digiq_partici_19c5c1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="digiquizratinghistory",
            constraint=models.UniqueConstraint(fields=("user", "round"), name="uq_digiquiz_rating_round_user"),
        ),
    ]
