# Generated by Django 5.2.9 on 2026-03-05 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_digiquiz_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheatReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("engine_use", "Engine Assistance"),
                            ("suspicious_play", "Suspicious Play"),
                            ("other", "Other"),
                        ],
                        default="engine_use",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("resolved_clean", "Resolved – Clean"),
                            ("resolved_cheating", "Resolved – Cheating"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheat_reports",
                        to="games.game",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheat_reports_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheat_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheat_reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheatAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t1_pct",
                    models.FloatField(
                        default=0, help_text="% moves matching engine top-1 choice"
                    ),
                ),
                (
                    "t2_pct",
                    models.FloatField(
                        default=0, help_text="% moves matching engine top-2"
                    ),
                ),
                (
                    "t3_pct",
                    models.FloatField(
                        default=0, help_text="% moves matching engine top-3"
                    ),
                ),
                (
                    "t4_pct",
                    models.FloatField(
                        default=0, help_text="% moves matching engine top-4"
                    ),
                ),
                (
                    "t5_pct",
                    models.FloatField(
                        default=0, help_text="% moves matching engine top-5"
                    ),
                ),
                ("avg_centipawn_loss", models.FloatField(default=0)),
                ("avg_winning_chances_loss", models.FloatField(default=0)),
                ("best_move_streak", models.IntegerField(default=0)),
                (
                    "accuracy_score",
                    models.FloatField(default=0, help_text="0-100 overall accuracy"),
                ),
                (
                    "position_stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="T% and ACPL broken down by position category (undecided/losing/winning/post_losing)",
                    ),
                ),
                (
                    "move_classifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Per-move breakdown: san, cp_loss, wcl, rank, is_forced, position_category, classification",
                    ),
                ),
                ("forced_moves_excluded", models.IntegerField(default=0)),
                ("book_moves_excluded", models.IntegerField(default=0)),
                (
                    "cp_loss_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Counts by bracket: {">0": N, ">10": N, ">25": N, ...}',
                    ),
                ),
                (
                    "suspicious_moves",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Moves in complex undecided positions that matched engine T1",
                    ),
                ),
                (
                    "irwin_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0-100 from Irwin NN, null if model untrained",
                        null=True,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("suspicious", "Suspicious"),
                            ("likely_cheating", "Likely Cheating"),
                        ],
                        default="clean",
                        max_length=30,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=0, help_text="0-1 confidence in verdict"),
                ),
                (
                    "full_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="Complete raw data including tensor features",
                        null=True,
                    ),
                ),
                ("total_moves_analyzed", models.IntegerField(default=0)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analyzed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheat_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheat_analyses",
                        to="games.game",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="games.cheatreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="IrwinTrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.BooleanField(help_text="True = cheating, False = clean"),
                ),
                (
                    "tensor_data",
                    models.JSONField(
                        help_text="8-feature x 60-move tensor + piece types for Irwin NN"
                    ),
                ),
                ("labeled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irwin_training",
                        to="games.game",
                    ),
                ),
                (
                    "labeled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irwin_labels_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irwin_training",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-labeled_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="cheatreport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "game"), name="uq_cheat_report_reporter_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="irwintrainingdata",
            constraint=models.UniqueConstraint(
                fields=("game", "player"), name="uq_irwin_training_game_player"
            ),
        ),
    ]
