# Generated by Django 5.2.9 on 2026-03-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_cheatreport_cheatanalysis_irwintrainingdata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="move_times_ms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-move elapsed time in milliseconds, one entry per ply",
            ),
        ),
    ]
